const getDefaultState = () => {
    return {
        dashboard: [
            {
                id: "LI-2021-0199 R02",
                link: "",
                type: "LI",
                vendor: "AGILITY (ABU DHABI) PJSC",
                attention: "Priyesh Thattarath",
                quotation: "MITME-AGL-01 (Appendix 1)",
                Status: "In Progress",
            },
            {
                id: "LI-2021-0203",
                link: "MR-2021-0134",
                type: "LI",
                vendor: "AGILITY (ABU DHABI) PJSC",
                attention: "Priyesh Thattarath",
                quotation: "MITME-AGL-01 (Appendix 1)",
                Status: "In Progress",
            },
            {
                id: "LI-2021-0213",
                link: "RRIN-2021-0054",
                type: "LI",
                vendor: "AGILITY (ABU DHABI) PJSC",
                attention: "Priyesh Thattarath",
                quotation: "MITME-AGL-01 (Appendix 1)",
                Status: "In Progress",
            },
            {
                id: "LI-2021-0218",
                link: "",
                type: "LI",
                vendor: "AGILITY (ABU DHABI) PJSC",
                attention: "Priyesh Thattarath",
                quotation: "MITME-AGL-01 (Appendix 1)",
                Status: "In Progress",
            },
            {
                id: "LI-2021-0219",
                link: "TRF-2021-0021",
                type: "LI",
                vendor: "AGILITY (ABU DHABI) PJSC",
                attention: "Priyesh Thattarath",
                quotation: "MITME-AGL-01 (Appendix 1)",
                Status: "In Progress",
            },
            {
                id: "LI-2021-0241",
                link: "RRIN-2021-0062",
                type: "LI",
                vendor: "AGILITY (ABU DHABI) PJSC",
                attention: "Priyesh Thattarath",
                quotation: "MITME-AGL-01 (Appendix 1)",
                Status: "In Progress",
            },
            {
                id: "LI-2021-0263",
                link: "",
                type: "LI",
                vendor: "AGILITY (ABU DHABI) PJSC",
                attention: "Priyesh Thattarath",
                quotation: "MITME-AGL-01 (Appendix 1)",
                Status: "In Progress",
            },
            {
                id: "LI-2021-0265 R01",
                link: "MR-2021-0171",
                type: "LI",
                vendor: "AGILITY (ABU DHABI) PJSC",
                attention: "Priyesh Thattarath",
                quotation: "MITME-AGL-01 (Appendix 1)",
                Status: "In Progress",
            },
            {
                id: "LI-2021-0266 R01",
                link: "MR-2021-0172",
                type: "LI",
                vendor: "AGILITY (ABU DHABI) PJSC",
                attention: "Priyesh Thattarath",
                quotation: "MITME-AGL-01 (Appendix 1)",
                Status: "In Progress",
            },
            {
                id: "LI-2021-0267 R01",
                link: "MR-2021-0173",
                type: "LI",
                vendor: "AGILITY (ABU DHABI) PJSC",
                attention: "Priyesh Thattarath",
                quotation: "MITME-AGL-01 (Appendix 1)",
                Status: "In Progress",
            },
            {
                id: "LI-2021-0268 R01",
                link: "",
                type: "LI",
                vendor: "AGILITY (ABU DHABI) PJSC",
                attention: "Priyesh Thattarath",
                quotation: "MITME-AGL-01 (Appendix 1)",
                Status: "In Progress",
            },
            {
                id: "LI-2021-0269",
                link: "",
                type: "LI",
                vendor: "AGILITY (ABU DHABI) PJSC",
                attention: "Priyesh Thattarath",
                quotation: "MITME-AGL-01 (Appendix 1)",
                Status: "In Progress",
            },
        ]
    }
}
